Upgraded out of date library imports
	there is a known issue with Werkzeug 1.X - had to revert to 0.16.1
	https://github.com/noirbizarre/flask-restplus/issues/777#issuecomment-583235327

	marshmallow 2.20 -> 3.5 causes:
		TypeError: __init__() takes 1 positional argument but 2 were given